In [1]:
import numpy as np
from numpy import genfromtxt # generate arrays from text

In [2]:
data = genfromtxt('../DATA/bank_note_data.txt', delimiter=',')

In [3]:
data # here we have features and labels

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
labels = data[:,4]

In [5]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features = data[:,0:4]

In [7]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

# Split the data into training and test set

In [8]:
X = features 
y = labels

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [11]:
X

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [12]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

## When working with neural networks its good to standardize your data. we can do that with function from sklearn

In [13]:
from sklearn.preprocessing import MinMaxScaler

### MinMaxScaler will force all features data to fall within certain range for neural network performs better

In [14]:
scaler_object = MinMaxScaler()

In [15]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [16]:
scaled_X_train = scaler_object.transform(X_train)

In [17]:
scaled_X_test = scaler_object.transform(X_test)

### The reason why we fit the scaler object only to the X_train instead of the whole datasets or data test is because we dont want our model to peek to the test data which is kinda cheating our model

In [40]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [41]:
model = keras.Sequential(
    [
        layers.Dense(4, input_dim=4, activation="relu", name="layer1"),
        layers.Dense(8, activation="relu", name="layer2"),
        layers.Dense(1, activation='sigmoid', name="layer3"),
    ]
)


In [42]:
# WE CAN ADD LAYERS

In [43]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [44]:
# Next we fit or train the model
model.fit(scaled_X_train, y_train, epochs=50, verbose=2) # 1 epochs gone through all the training data 1 time

Train on 919 samples
Epoch 1/50
919/919 - 1s - loss: 0.6773 - accuracy: 0.5495
Epoch 2/50
919/919 - 0s - loss: 0.6733 - accuracy: 0.5495
Epoch 3/50
919/919 - 0s - loss: 0.6692 - accuracy: 0.5495
Epoch 4/50
919/919 - 0s - loss: 0.6645 - accuracy: 0.5495
Epoch 5/50
919/919 - 0s - loss: 0.6592 - accuracy: 0.5495
Epoch 6/50
919/919 - 0s - loss: 0.6533 - accuracy: 0.5495
Epoch 7/50
919/919 - 0s - loss: 0.6461 - accuracy: 0.5495
Epoch 8/50
919/919 - 0s - loss: 0.6379 - accuracy: 0.5495
Epoch 9/50
919/919 - 0s - loss: 0.6283 - accuracy: 0.5647
Epoch 10/50
919/919 - 0s - loss: 0.6170 - accuracy: 0.5713
Epoch 11/50
919/919 - 0s - loss: 0.6046 - accuracy: 0.5734
Epoch 12/50
919/919 - 0s - loss: 0.5909 - accuracy: 0.5985
Epoch 13/50
919/919 - 0s - loss: 0.5754 - accuracy: 0.6366
Epoch 14/50
919/919 - 0s - loss: 0.5592 - accuracy: 0.7236
Epoch 15/50
919/919 - 0s - loss: 0.5420 - accuracy: 0.7813
Epoch 16/50
919/919 - 0s - loss: 0.5246 - accuracy: 0.8248
Epoch 17/50
919/919 - 0s - loss: 0.5069 - ac

In [45]:
# now we do that to the test set because the test set is basically the data that we would like to predict 

In [46]:
model.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    

In [47]:
# we can check if its performs well by evaluate our model

In [48]:
model.metrics_names

['loss', 'accuracy']

In [49]:
from sklearn.metrics import confusion_matrix, classification_report

In [50]:
predictions = model.predict_classes(scaled_X_test)

In [51]:
confusion_matrix(y_test, predictions)

array([[253,   4],
       [ 14, 182]], dtype=int64)

In [52]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.95      0.98      0.97       257
         1.0       0.98      0.93      0.95       196

    accuracy                           0.96       453
   macro avg       0.96      0.96      0.96       453
weighted avg       0.96      0.96      0.96       453



# Save our model

In [53]:
model.save('mysupermodel.h5')

In [54]:
newmodel = keras.models.load_model('mysupermodel.h5')

In [55]:
newmodel.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    